### ISSUE TITLE
How to define a hierarchical B-Splinebase on a bounded domain?

### ISSUE THREAD

**Issue by skyforcen73** [gismo/gismo#13]
Hello everybody,

i would like to use hierarchical B-Splines for scattered data approximation on bounded domains like on a unit circle.

The tutorials like "tutorialTHBSplineBasis.cpp" or "fitting_example.cpp" give you the idea how to define hierarchical B-Splines on a n-dimensional box. But to ensure the linear independence of B-Splines of different levels the refinement procedure has to consider the bounded domain, which is in many cases not a rectangle.

With another words: is there any method like "refineElements" with regarding to the bounded domain?

many thanks in advance!
skyforce

**Comment by filiatra** [comment]
Closing this issue, since it is rather old. Open a new one if needed, here is a page explainging THB splines
https://gismo.github.io/thbSplineBasis_example.html
