### ISSUE TITLE
Realize the simulation of a geometry defined by a .3dm file.

### ISSUE THREAD

**Issue by TJUZMX** [gismo/gismo#158]
Hello

Could I import a geometry from a .3dm file and realize the simulation? 
How can I do it? Any suggestions are gratefully accepted.

Best regards

**Comment by filiatra** [comment]
Hi, you should add the argument -DGISMO_WITH_ONURBS=ON to the CMake line.
Note that only selected entities are imported from 3dm files (i.e. B-splines)
Try to run gsView opening a 3dm file to see if things are loaded fine.
