### ISSUE TITLE
Generalized eigenproblem in gismo with sparse-complex matrix

### ISSUE THREAD

**Issue by thanhchuong8252** [gismo/gismo#162]
Dear all,
 I am using gismo for calculating band-structure , do any one are able to calculate eigen-values and corresponding eigen-vector of the generalize eigenproblem (K-w*M)*U=0, where matrix K is complex number?
thank you very much.

**Comment by filiatra** [comment]
Hi,
you can do that by using spectra, ie add the argument GISMO_WITH_SPECTRA=ON to cmake.
Then you can use the classes defined in 
https://github.com/gismo/gismo/blob/stable/extensions/gsSpectra/gsSpectra.h

**Comment by thanhchuong8252** [comment]
thank you, let me try and report the issues
