### ISSUE TITLE
Robin boundary example missing

### ISSUE THREAD

**Issue by jobordu** [gismo/gismo#167]
Hi everybody, 

New user of G+Smo here :). 

I'm trying to modify the poisson_example.cpp to have Robin boundary without success.

The documentation is not clear on how to define the gsFunctionExpr for the Robin boundary.

Jonathan

**Comment by jobordu** [comment]
@filiatra @stefantakacs are Robin Boundaries supported by G+Smo ?

**Comment by jobordu** [comment]
Can we now apply robin boundaries ? @filiatra @stefantakacs

**Comment by hverhelst** [comment]
@jobordu is this still relevant for you?
