### ISSUE TITLE
How to Solve Elasticity Problems

### ISSUE THREAD

**Issue by AzerH66** [gismo/gismo#18]
Hello
I studied "tutorialAssembly" now I would like to apply gismo in solving elasticity problems, I mean problems with two degrees of freedom.
Should I use "gsPde" ?? or is there any way to assemble system and apply boundary conditions?

I appreciate any help that you can provide
hamidreza

**Comment by teymurheydarov** [comment]
@Shamanskiy , maybe, your class would be of help? Or is it in unsupported part?

**Comment by hverhelst** [comment]
Hey @AzerH66 , is this question still relevant for you? We have the module `gsElasticity`, which you can find here: https://github.com/gismo/gsElasticity.
