### ISSUE TITLE
Compile with GCC 7.3.0 fails on Release builds

### ISSUE THREAD

**Issue by codewerfer** [gismo/gismo#227]
At the moment, GCC 7.3.0 has a bug that prevent from successfully compile of gismo.

GCC 6.4.0 could be used instead.

**Comment by filiatra** [comment]
Can you send a link with this bug mention/report ?

**Comment by filiatra** [comment]
https://cdash.ricam.oeaw.ac.at/viewBuildError.php?buildid=300162

**Comment by filiatra** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1544650

**Comment by codewerfer** [comment]
Also:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82795
https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=84152

Should work from 7.3.1 upwards..

**Comment by weinmueller** [comment]
The bug of the problem should shown as
...
[ 46%] Building CXX object src/CMakeFiles/gsSolver.dir/gsSolver/gsPatchPreconditionersCreator_.cpp.o
In file included from /home/riemann/weinmueller/gismo/external/Eigen/SparseCore:59:0,
                 from /home/riemann/weinmueller/gismo/external/Eigen/Sparse:26,
                 from /home/riemann/weinmueller/gismo/src/gsCore/gsLinearAlgebra.h:42,
                 from /home/riemann/weinmueller/gismo/src/gsCore/gsBoundary.h:16,
                 from /home/riemann/weinmueller/gismo/src/gsCore/gsDofMapper.h:17,
                 from /home/riemann/weinmueller/gismo/src/gsAssembler/gsAssembler.h:18,
                 from /home/riemann/weinmueller/gismo/src/gsSolver/gsPatchPreconditionersCreator.h:15,
                 from /home/riemann/weinmueller/gismo/src/gsSolver/gsPatchPreconditionersCreator_.cpp:1:
/home/riemann/weinmueller/gismo/external/Eigen/src/SparseCore/SparseSelfAdjointView.h: In function 'void Eigen::internal::permute_symm_to_symm(const MatrixType&, Eigen::SparseMatrix<typename MatrixType::Scalar, DestOrder, typename MatrixType::StorageIndex>&, const typename MatrixType::StorageIndex*) [with int SrcMode = 1; int DstMode = 2; MatrixType = Eigen::SparseMatrix<double, 0, int>; int DestOrder = 0]':
/home/riemann/weinmueller/gismo/external/Eigen/src/SparseCore/SparseSelfAdjointView.h:517:6: internal compiler error: in predicate_mem_writes, at tree-if-conv.c:2252
 void permute_symm_to_symm(const MatrixType& mat, SparseMatrix<typename MatrixType::Scalar,DstOrder,typename MatrixType::StorageIndex>& _dest, const typename MatrixType::StorageIndex* perm)
      ^~~~~~~~~~~~~~~~~~~~

**Comment by codewerfer** [comment]
No, it's still there, see https://cdash.ricam.oeaw.ac.at/viewBuildError.php?buildid=317695
GCC 7.3.0 against d8aadd939431d67235d6783c8b4ba71e95a75afd

**Comment by filiatra** [comment]
Indeed, it still fails - I had a wrong impression, thanx for testing!
