### ISSUE TITLE
Solving a heat equation on a surface failed.

### ISSUE THREAD

**Issue by YuCrazing** [gismo/gismo#283]
I make a patch R^2 -> R^3, to solve the heat equation on a surface, but get a runtime error. So, how to solve a heat equation on a surface?

**Comment by dominik-mokris-mtu** [comment]
The cause is difficult to guess at. Can you share a MWE (minimal working example) so that we can see what exactly you do?

**Comment by hverhelst** [comment]
@YuCrazing is this still relevant? Otherwise we close the issue.
