### ISSUE TITLE
Linker errors in gsElasticity

### ISSUE THREAD

**Issue by Shamanskiy** [gismo/gismo#292]
I checked out the latest version of stable, and the linker error appeared when trying to compile gsElasticity/examples. 
The library itself compiles, the error appears only when compiling executables:
![Screenshot from 2019-03-19 13-42-44](https://user-images.githubusercontent.com/29507068/54606801-12cef100-4a4d-11e9-8624-0ad8399a307c.png)

May it be related to some recent changes in CMake files?

P.S. If you want to check it, don't forget to fetch the latest version of gsElasticity manually, it is not yet in gismo-stable

**Comment by codewerfer** [comment]
**Yes**, there is something wrong with the includes - did not know at the moment why exactly it is.
(gsElasticityAssembler{.h,.hpp,_.cpp} exists)

For the `gsElasticityAssembler` stuff, it works - but this is not the fix! - if you change [line 3](https://github.com/gismo/gsElasticity/blob/master/examples/linElast2D_lshape.cpp#L3) to:
```c++
#include <gsElasticity/gsElasticityAssembler.hpp>
```

Keeps us up with `linElast2D_lshape.cpp:103: undefined reference to `void gismo::gsWriteParaviewMultiPhysics<double>(`
There the same include stuff.

If we grep for the build object file - and compare the result with one where we know it works, we see that it is missing in some `build/CMakeFiles/<???>/link.txt` file.

> May it be related to some recent changes in CMake files?

I think also so.
Btw. to get a better view in github to compare latest with known working hash, use this link:
https://github.com/gismo/gsElasticity/compare/78a79ae00e5b8551275a2c6f7b278b129b660357...master
