### ISSUE TITLE
Bug in basis_example.cpp

### ISSUE THREAD

**Issue by mingzengliu** [gismo/gismo#294]
I encountered an internal problem, which may  be related to Eigen;
My OS: macOS Mojave v10.14.3
xcode: v10.2(10E125)
gismo: the current stable version:
             https://github.com/gismo/gismo/wiki/Downloads

I build gismo as follows:
cd gismo-stable
make
make install

Then I test the basis_example.cpp in Xcode, 
by adding header path: /usr/local/include/gismo
     adding lib paths:       /usr/local/lib
and link binary lib: libgismo.a

The error occurs when i build the basis_example.cpp:(gsbasis is the name of my xcode project)

gsbasis(18030,0x1000d25c0) malloc: *** error for object 0x101b3e760: pointer being freed was not allocated
gsbasis(18030,0x1000d25c0) malloc: *** set a breakpoint in malloc_error_break to debug
(lldb) 

in fact, the when the program run : gsMatrix<> support = pBasis->support();
the error occurs.

How do i fix the error?

**Comment by mingzengliu** [comment]
I fixed the problem. 
Just only compile the gismo library in RelWithDebInfo instead of Release mode.

**Comment by codewerfer** [comment]
What compiler do you use? What version?
