### ISSUE TITLE
Active functions are not necessarily non-zero in a point.

### ISSUE THREAD

**Issue by sofimp23** [gismo/gismo#322]
Dear all,

it seems to me that the function `gsHTensorBasis::active_into` is doing something slightly different from what the documentation says.

The documentation says:

> Returns the indices of active (non-zero) basis functions at points u, as a list of indices, in result.

However, it seems that it returns the indices of functions whose support (when defined as the _closure_ of the set of points where the function is non-zero) contains the point. When I run the following code

    int main()
    {
        gsKnotVector<real_t> kv(0, 1, 0, 2); 
        gsTensorBSplineBasis<2, real_t> tens_basis(kv, kv);
    
        gsMatrix<real_t> u(2,1);
        u(0,0) = 0;
        u(1,0) = 1;
    
        gsMatrix<unsigned> Indices_active;
        tens_basis.active_into(u, Indices_active);
        gsInfo << "Indices of the active functions in (0,1):\n" << Indices_active << "\n";
    
       gsMatrix<real_t> Values_active;
       tens_basis.eval_into(u, Values_active);
       gsInfo << "Values of the active functions in (0,1):\n" << Values_active << "\n"; 
    }

there should be just one active function in `(0,1)`, while the result is

    Indices of the active functions in (0,1):
    0
    1
    2
    3
    Values of the active functions in (0,1):
    0
    0
    1
    0

Shall I improve the documentation or am I missing something?

**Comment by filiatra** [comment]
Yes that is true, the returned values is as you say. You can add this as a note in the documentation.
In fact the correction could be:



    Returns the indices of active (non-zero, or with non-zero derivatives) basis functions at points u, as a list of indices, in result.

In certain cases, extra indices are returned. In that case the eval function returns a zero value/derivative for the corresponding bases functions.

**Comment by sofimp23** [comment]
Good. Do I have to create a branch and pull request or can I push it directly to master?

**Comment by codewerfer** [comment]
No direct push to `master` (called `stable` under gismo/gismo) is allowed, please create a branch and do the usual pull request as you expected already.

**Comment by dominik-mokris-mtu** [comment]
Will be closed when pull request #341 gets approved.

**Comment by dominik-mokris-mtu** [comment]
Solved in the pull request #341.
