### ISSUE TITLE
gsKnotVector is not consistent when constructed with non-clamped knots

### ISSUE THREAD

**Issue by sofimp23** [gismo/gismo#324]
We had a discussion with @dominik-mokris-mtu about knot vectors that are not clamped. And we believe that we have found a bug in `gsKnotVector`.

When you create a `gsKnotVector` with

    gsKnotVector<real_t> kv(0, 1, 3, 1, 1, 2);

the contents of `m_repKnots` is `0 -0.5 -0.25 0.25 0.5 0.75 1 1.25 1.5` and `m_multSum` contains `1 1 1 2 3 4 5 1 1`. Consequently, the `GISMO_ASSERT` on line 659 in `gsKnotVector.hpp` fails.

Based on our understanding, the correct values are the following:

    -0.5 -0.25 0 0.25 0.5 0.75 1 1.25 1.5
    1 2 3 4 5 6 7 8 9

We propose fixing it with replacing the lines 635 till 657 in gsKnotVector.hpp with

    for(unsigned i = m_deg - mult_ends + 1; i!= 0; --i)
    {   // add left ghost knots
        m_repKnots.push_back(first-i*h);
        m_multSum .push_back(m_multSum.back() + 1);
    }

    m_repKnots.insert(m_repKnots.end(), mult_ends, first);
    m_multSum .push_back(m_multSum.back() + mult_ends);

    for( unsigned i=1; i<=interior; ++i)
    {
        m_repKnots.insert( m_repKnots.end(), mult_interior, first + i*h );
        m_multSum .push_back( mult_interior + m_multSum.back() );
    }

    m_repKnots.insert( m_repKnots.end(), mult_ends, last );
    m_multSum .push_back( mult_ends + m_multSum.back() );

    for(unsigned i = 1; i!=m_deg - mult_ends + 2; ++i)
    {   // add right ghost knots
        m_repKnots.push_back(last+i*h);
        m_multSum .push_back(m_multSum.back() + 1);
    }

We will run more tests on it to confirm.

Is our understanding correct?

**Comment by filiatra** [comment]
Yes, I think your understanding is correct. Please make a branch and a pull request so the stable branch..
thanx

**Comment by dominik-mokris-mtu** [comment]
Will be closed if pull request #341 gets approved.

**Comment by dominik-mokris-mtu** [comment]
Solved in the pull request #341.
