### ISSUE TITLE
The body of `get_level(unsigned)` seems to be missing.

### ISSUE THREAD

**Issue by dominik-mokris-mtu** [gismo/gismo#345]
Hi:
consider the following code snippet.

    #include <gismo.h>
    
    using namespace gismo;
    
    int main()
    {
        gsKnotVector<> kv(0,1,0,3);
        gsTHBSplineBasis<2> thBasis(gsTensorBSplineBasis<2>(kv,kv));
        gsInfo << "Level of function nr.0: " << thBasis.get_level(0) << std::endl;
        return 0;
    }

It compiles but fails to link with the following error message

    gismo/extensions/unsupported/examples/issue_344.cpp:9: undefined reference to `gismo::gsHTensorBasis<(short)2, double>::get_level(unsigned int) const'
    collect2: error: ld returned 1 exit status

To my surprise, neither me, nor @sofimp23, nor `grep` were able to localize the body of the function `get_level`. Furthermore, judging by its documentation
> Returns the level of _function_, which is a hier. Id index.

it seems to duplicate the functionality of `levelOf`, which
>Returns the level of the function indexed _i_ (in continued indices)

**Question** Am I right to conclude that the declaration should be deleted?

P.S.: `grep` also found the line

     if(omp_get_level()!=0)
in gsIETIAssembler.h. Although it is in devel, it might be worth having a closer look as well, as it might lead to a similar problem.

**Comment by filiatra** [comment]
omp_get_level() is something different (openmp call).

Yes this was probably an old version of levelOf, removed now 2b7066e

There used to be a check during compilation, signalling undefined functions...
