### ISSUE TITLE
Function refineElements does not work for gsTHBSplineBasis without clamped knots.

### ISSUE THREAD

**Issue by dominik-mokris-mtu** [gismo/gismo#350]
The following code should construct a THB-spline basis without clamped knots and refine it.

```cpp
#include <gismo.h>

using namespace gismo;

int main()
{
    // Knot vector for a quadratic basis without clamped knots.
    gsKnotVector<real_t> kv(-0.5,1.5,7,1);
    kv.set_degree(2);

    gsTensorBSplineBasis<2, real_t> ten(kv, kv);
    gsTHBSplineBasis<2> thb(ten);

    std::vector<index_t> box;
    box.push_back( 1 );
    box.push_back( 0 );
    box.push_back( 0 );
    box.push_back( 8 );
    box.push_back( 8 );
    thb.refineElements(box);

    gsInfo << thb << std::endl;

    return 0;
}
```
However, it does not go through:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  GISMO_ASSERT `i>=0 && i<m_size` 
/home/cpfscae07/disk00100/disk00101/ya10813/gismo/external/Eigen/src/SparseCore/SparseVector.h, line 127 (coeffRef)
Aborted
```

After quite some chase throught the source code I was able to pinpoint the cause of the behaviour to the lines 783 and 784 in gsKnotVector.hpp.
```cpp
    if (0!=l) trimLeft (l);
    if (0!=r) trimRight(r);
```
These two cause the level 1 knot vector of to be
```
[ -0.25 -0.1875 -0.125 -0.0625 0 ... 1 1.0625 1.125 1.1875 1.25 ] (deg=2, size=25, minSpan=0.0625, maxSpan=0.0625)
```
instead of
```
[ -0.5 -0.4375 -0.375 -0.3125 -0.25 ... 1.25 1.3125 1.375 1.4375 1.5 ] (deg=2, size=33, minSpan=0.0625, maxSpan=0.0625)
```
that I would expect. That is, the _domain_ of the knot vector (the interval between the (`deg+1`)-st from the beginning and `(deg+1)`-st knot from the end) remains the same but the _first_ and _last_ knots shrink closer to each other.

Uncommenting these two lines not only alleviated the problem but it also solved issue #10 (which is how I got to this problem in the first place).

What shall we do? My suggestion would be to get rid of those two lines but I suppose they are there for a reason.

**Comment by osmihran** [comment]
I confirm that PR #402 seems to fix this issue, the code runs and gives plausible results.
(Edit: I changed `unsigned` to `index_t` in the example.)
