### ISSUE TITLE
what is the sequence of control points in tcoefs?

### ISSUE THREAD

**Issue by ohehe** [gismo/gismo#364]
If I use the constructor of `gsTensorBSpline( KnotVectorType KV1,KnotVectorType KV2,KnotVectorType KV3,gsMatrix<T> tcoefs )` to generate Bspline volume, what is the sequence of control points in `gsMatrix<T> tcoefs` ?

**Comment by filiatra** [comment]
Every row in the matrix is one control point.  The order of the rows
is reverse lexicographic: the first index runs faster, then the second
and so on.
For example a 3D triliner spline with knotvector (0,0,1,1) in each
coordinate has the following coefficient matrix:

x000 y000 z000 
x100 y100 z100
x010 y010 z010 
x110 y110 z110 
x001 y001 z001 
x101 y101 z101 
x011 y011 z011 
x111 y111 z111 

where index ijk corresponds to the tensor-product basis function Bi*Bj*Bk.
