### ISSUE TITLE
component basis

### ISSUE THREAD

**Issue by miaozhongfeng** [gismo/gismo#373]
How do I compute the component basis functions of a single basis function？

**Comment by filiatra** [comment]
Having a gsTensorBasis object, you can obtain the multi-index of a basis function with:
gsTensorBasis::tensorIndex
https://gismo.github.io/classgismo_1_1gsTensorBasis.html#a74caa9469576171422837c8cefb83be4

Then you can obtain the component basis function for coordinate "i" by first grabing 
gsTensorBasis::component
https://gismo.github.io/classgismo_1_1gsBasis.html#a86da66270c151d017f8604b8c4a3a192

and then calling
gsBSplineBasis::function
https://gismo.github.io/classgismo_1_1gsBasis.html#aa6b63b1a93801d7ac34dc809e7123727

with argument the corresponding tensor-index.
