### ISSUE TITLE
How to check the data in gsMatrix under debug mode of MS visual studio?

### ISSUE THREAD

**Issue by snakegit** [gismo/gismo#407]
Hi,
During debug with MS Visual studio, the data within gsMatrix cannot be obtained. Only the first value in m_data can be seen, and the other values are not available. Is there any method to obtain the whole contents of gsMatrix during debug?

**Comment by snakegit** [comment]
I think I got a solution now.
(1) check this https://github.com/cdcseacave/Visual-Studio-Visualizers#readme 
Download Eigen debug visualizers "eigen.natvis". 
(2) The file is typically copied to %VSINSTALLDIR%\Common7\Packages\Debugger\Visualizers, where %VSINSTALLDIR% is the Visual Studio installation folder.

**Comment by filiatra** [comment]
That is great information thanx!
