### ISSUE TITLE
Is the parameter matrix of the thb splines basis at Greville points invertible?

### ISSUE THREAD

**Issue by arungoooo112** [gismo/gismo#470]
Dear all.

Given a set  {a1, a2, ... , an} of points of size n defined at the Greville abscissae
corresponding to the thb spline basis function. There is a matrix K(n, n),  which 
ith row is the value of thb spline basis at ai.

![image](https://user-images.githubusercontent.com/61907503/132473561-f671c086-5ad3-42bf-8855-5f65a476c76a.png)

I want to know if the matrix K invertible? I know K is invertible for nurbs basis. [](url)
I checked some papers related to thb and didn't find this proof. 
After that I tried to prove it myself, but failed.

If you know anything about this issue, please give me some help.

**Comment by filiatra** [comment]
Hi,
No it is not invertible, simply because you may get the same point twice in differnt levels (therefore same row twice).
One needs to somehow define distinct points, currently this is not the case in G+Smo's implementation.
It is in our list to derive a better implementation (and ideas are mostly welcome!).

**Comment by arungoooo112** [comment]
Thanks!
I find the same points in different levels when degree p == 3.
As you mentioned above, I also think it is necessary to define 
distinct points associated with the (t)hb basis functions.

Now, for simplicity, limit degree  p= 2. Then we can't find the same points.
So I want to ask again,  if the matrix K invertible? 

: )
Frank.

**Comment by filiatra** [comment]
Hi,
well for even degree the points are distinct, so there is chance that the matrix is invertible.
But I am not aware of a theoretical result. You can easily test examples by creating the matrix
basis.collocationMatrix( basis.anchors(), result)
and then checking whether "result" is invertible.

**Comment by osmihran** [comment]
I suggest closing this issue, as it is not really about G+Smo but rather the theory of THB-splines.
