### ISSUE TITLE
Gismo compilation flags

### ISSUE THREAD

**Issue by saidctb** [gismo/gismo#474]
Dear all,
I want to compile gismo with specific flags, is there a way to do that?

**Comment by filiatra** [comment]
Hi,

to add specific flags before doing the CMake configuration you need to set enviromental variables CFLAGS and CXXFLAGS.
Anything you add there will be picked up by CMake.

Example: in Linux adding the gddb flag is as follows:
export CFLAGS=-ggdb
export CXXFLAGS=-ggdb

**Comment by saidctb** [comment]
thanks for your help
