### ISSUE TITLE
Submodule gsCompFlow@c49c94b is a broken link

### ISSUE THREAD

**Issue by yurivict** [gismo/gismo#492]

**Comment by filiatra** [comment]
this is normal, the modules are not meant to be included in the distrubution.

**Comment by yurivict** [comment]
> this is normal, the modules are not meant to be included in the distrubution.

No, this means that this submodule is unfetchable because it's a broken link - no such repository.

**Comment by mmoelle1** [comment]
These are private repos that are not available to the public. We will migrate them to the new fetching mechanism so that they don't appear as submodules any more. With that fetching mechanism we can inform the user about this restricted access when using one of the switches.
