### ISSUE TITLE
Function slice gives wrong results for par = 1.0

### ISSUE THREAD

**Issue by osmihran** [gismo/gismo#504]
Function `gsTensorBSpline<T>::slice(index_t, T, BoundaryGeometryType&)` gives wrong result when using the highest possible value of the fixed parameter.

### Example to reproduce
```cpp
#include <gismo.h>

using namespace gismo;

int main()
{
    // Create a simple tensor-product spline.
    gsMatrix<real_t> coefs(4, 2);
    coefs << 0, 0,
	1, 0,
	0, 1,
	1, 1;
    gsKnotVector<real_t> KV(0.0, 1.0, 0, 2);
    gsTensorBSpline<2, real_t> spline(KV, KV, coefs);

    // Write it out.
    gsWriteParaview(spline, "spline");

    // Construct three its slices.
    gsBSpline<real_t> slice01, slice09, slice10;
    spline.slice(1, 0.1, slice01);
    spline.slice(1, 0.9, slice09);
    spline.slice(1, 1.0, slice10);

    // Write them out.
    gsWriteParaview(slice01, "slice01");
    gsWriteParaview(slice09, "slice09");
    gsWriteParaview(slice10, "slice10");

    return 0;
}
```
Here is what the slices at 0.1, 0.9 and 1.0 look like in Paraview coloured in red, green and blue, respectively.
![issue-504](https://user-images.githubusercontent.com/39057965/148408085-02431118-6819-4079-bc4c-23c403cb246d.png)

**Expected behaviour:** the blue line is at the _top_ of the square.
**Actual behaviour:** the blue line is at the _bottom_ of the square.

**Comment by filiatra** [comment]
Hi, hopefully this is fixed in the above commit (if so, please close the issue).

**Comment by osmihran** [comment]
Thanks! It works, both in the example that I committed and another one I kept locally to test it.
