### ISSUE TITLE
Please add FreeBSD to the 'Operating systems' section in README

### ISSUE THREAD

**Issue by yurivict** [gismo/gismo#509]
The FreeBSD port is available: https://www.freshports.org/math/gismo/

**Comment by yurivict** [comment]
Thank you!

**Comment by mmoelle1** [comment]
@yurivict I am heavily revising the `OptimizationForArchitecture.cmake` script in the `xbraid` branch. With your help I can add support for FreeBSD (or BSD in general). I am familiar with Darwin's `sysctl` command to retrieve system information. Would would be the BSS way to get `vendor_id`, `cpu_model`, `cpu_family` and `cpu_stepping` on x86_64 systems?

I am also working on supporting arm and arm64 (aarch64). What would be the `sysctl` command to get `cpu_implementer`, `cpu_architecture`, `cpu_variant`, `cpu_part`, and `cpu_revision`?

Please do not commit patches to the current version of the script as I am splitting it up into multiple files.

**Comment by yurivict** [comment]
> I am heavily revising the OptimizationForArchitecture.cmake script in the xbraid branch. With your help I can add support for FreeBSD (or BSD in general). I am familiar with Darwin's sysctl command to retrieve system information. Would would be the BSS way to get vendor_id, cpu_model, cpu_family and cpu_stepping on x86_64 systems?


Please consider the [hwloc2](https://www.open-mpi.org/projects/hwloc/) project for this. It provides detailed information about CPU. Otherwise it's the ```sysctl``` system call.

**Comment by mmoelle1** [comment]
@yurivict I know hwloc2 but that is not a default package that we can expect to be installed on every system. I have setup a FreeBSD VM to test the OFA script. It turns out `sysctl` does not give me any processable information about the cpu model, family, stepping. Only the cpu model string is provided, e.g.,
```
sysctl hw.model hw.machine hw.ncpu
hw.model: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
hw.machine: amd64
hw.ncpu: 1
```
Is there any other way to get the information with system tools.

**Comment by hverhelst** [comment]
@mmoelle1 @filiatra @yurivict there are quite some Issues related to FreeBSD: #496, #495, #466. Are they all still relevant? Or could we also close those, since this issue is closed?
