### ISSUE TITLE
(Strong) Enforcement of Dirichlet BCs of second type for the biharmonic eq.

### ISSUE THREAD

**Issue by nilskohl** [gismo/gismo#513]
Hi,

I would like to enforce Dirichlet BCs of second type for the biharmonic eq., i.e. solve (for example in 1D, homogeneous BCs)

```
 u'''' = f    in \Omega
u = u' = 0    on \partial \Omega
```

While the class `gsBiharmonicAssembler` suggests that this is possible, it appears that the implementation is empty/commented out:

https://github.com/gismo/gismo/blob/df719ccc79424e75f0e1fbcf8ba1863de3c9b127/src/gsAssembler/gsBiharmonicAssembler.hpp#L57

After removing the comments the biharmonic example does not compile anymore so it seems there is more to fix.

For the moment I would be satisfied with strong enforcement of _homogeneous_ BCs, e.g. by (manual) modification of the system matrix and rhs (which is going to be my next attempt). Is there any better way to achieve this?

Cheers,
Nils

**Comment by weinmueller** [comment]
Hello Nils,

currently I am also working with biharmonic (also for multi-patches, where you need the C^1 smoothness) with different boundary conditions, e.g. Dirichlet, Neumann and Laplace, even with non-homogeneous boundaries. Somehow the biharmonic_example is unfortunately not the current one. If you want, I can show you the file.

Greetings
Pascal

**Comment by nilskohl** [comment]
Hi Pascal,

that would be nice. 

For the moment I could handle the problem manually, although with a kind of "hacky" manipulation of the system matrix.
So a cleaner solution would still be appreciated.

Cheers,
Nils

**Comment by weinmueller** [comment]
Sure no problem. Right now, we are preparing the example for the stable. Here you can follow the process: #518

**Comment by weinmueller** [comment]
If you have further questions about the biharmonic problem, you are very welcome to ask me.
