### ISSUE TITLE
GitHub actions are failing on Ubuntu

### ISSUE THREAD

**Issue by dominik-mokris-mtu** [gismo/gismo#555]
I have had a closer look at why Github actions are sometimes failing. In [this case](https://github.com/gismo/gismo/actions/runs/3271607569) the tests are compiled on Ubuntu in **RelWithDebInfo** and the example **constrained_fitting** then fails due to a timeout.

I can see two options for fixing it:

1. Increase the time limit. Currently, it is 200s (as set on line 145 of **cmake/ctest_script.cmake**) but it would need to increase to maybe 10min (600s), which is quite a lot.
2. Decrease the number of iterations (line 27 of **examples/constrained_fitting.cpp**) to 2 or maybe 3. That should be enough to test the functionality.

Either of the changes is probably way too small for a separate PR, so we might add it to some upcoming PR ..?

**Comment by filiatra** [comment]
There was a bug in a recent commit, now constrained_fitting. works again
