### ISSUE TITLE
gsOpenNurbs does not compile with newer GCC

### ISSUE THREAD

**Issue by dominik-mokris-mtu** [gismo/gismo#556]
While testing the **remove_submodules** branch I have encountered a problem that I can now reproduce in **stable** as well. When trying to compile with gsOpenNurbs with newer `g++` versions, the compilation crashes with the following error message:

```
[ 80%] Building C object extensions/gsOpennurbs/CMakeFiles/gsOpennurbs.dir/__/__/external/onurbs/opennurbs_memory.c.o
cc: error: unrecognized command line option ‘-mno-avx512bf16’; did you mean ‘-mno-avx512bw’?
cc: error: unrecognized command line option ‘-mno-avx512bitalg’; did you mean ‘-mno-avx5124fmaps’?
cc: error: unrecognized command line option ‘-mno-avx512vbmi2’; did you mean ‘-mno-avx512vbmi’?
cc: error: unrecognized command line option ‘-mno-avx512vnni’; did you mean ‘-mno-avx5124vnniw’?
cc: error: unrecognized command line option ‘-mno-avx512vp2intersect’; did you mean ‘-mno-avx512vpopcntdq’?
cc: error: unrecognized command line option ‘-mno-avx512bf16’; did you mean ‘-mno-avx512bw’?
cc: error: unrecognized command line option ‘-mno-avx512bitalg’; did you mean ‘-mno-avx5124fmaps’?
cc: error: unrecognized command line option ‘-mno-avx512vbmi2’; did you mean ‘-mno-avx512vbmi’?
cc: error: unrecognized command line option ‘-mno-avx512vnni’; did you mean ‘-mno-avx5124vnniw’?
cc: error: unrecognized command line option ‘-mno-avx512vp2intersect’; did you mean ‘-mno-avx512vpopcntdq’?
cc: error: unrecognized command line option ‘-mno-avx512bf16’; did you mean ‘-mno-avx512bw’?
cc: error: unrecognized command line option ‘-mno-avx512bitalg’; did you mean ‘-mno-avx5124fmaps’?
cc: error: unrecognized command line option ‘-mno-avx512vbmi2’; did you mean ‘-mno-avx512vbmi’?
cc: error: unrecognized command line option ‘-mno-avx512vnni’; did you mean ‘-mno-avx5124vnniw’?
cc: error: unrecognized command line option ‘-mno-avx512vp2intersect’; did you mean ‘-mno-avx512vpopcntdq’?
make[3]: *** [extensions/gsOpennurbs/CMakeFiles/gsOpennurbs.dir/build.make:1445: extensions/gsOpennurbs/CMakeFiles/gsOpennurbs.dir/__/__/external/onurbs/opennurbs_memory.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1843: extensions/gsOpennurbs/CMakeFiles/gsOpennurbs.dir/all] Error 2
```

**Tested compilers**
- [x] g++ 7.5.0 (SUSE Linux) compiles without problem 
- [ ] g++ 8.3.1 (SUSE Linux) crashes
- [x] g++ 9.4.0 (Ubuntu 20.04) compiles without problem (!)
- [ ] g++ 11.2.0 (SUSE Linux) crashes
- [ ] clang 10.0 (Ubuntu 20.04) crashes
- [ ] clang 11.0.1 (SUSE Linux) crashes

**Steps to reproduce**

1. Checkout G+Smo;
2. configure with `cmake ../gismo -DCMAKE_BUILD_TYPE=Release -DGISMO_BUILD_UNITTESTS=ON -DGISMO_WITH_ONURBS=ON -DCMAKE_CXX_COMPILER=/path/to/g++`;
4. compile with `make unittests -j 8`

**Comment by mmoelle1** [comment]
I am working on that.

On 25 Oct 2022, at 16:19, Dominik Mokriš - work account ***@***.******@***.***>> wrote:



While testing the remove_submodules branch I have encountered a problem that I can now reproduce in stable as well. When trying to compile with gsOpenNurbs with newer g++ versions, the compilation crashes with the following error message:

[ 80%] Building C object extensions/gsOpennurbs/CMakeFiles/gsOpennurbs.dir/__/__/external/onurbs/opennurbs_memory.c.o
cc: error: unrecognized command line option ‘-mno-avx512bf16’; did you mean ‘-mno-avx512bw’?
cc: error: unrecognized command line option ‘-mno-avx512bitalg’; did you mean ‘-mno-avx5124fmaps’?
cc: error: unrecognized command line option ‘-mno-avx512vbmi2’; did you mean ‘-mno-avx512vbmi’?
cc: error: unrecognized command line option ‘-mno-avx512vnni’; did you mean ‘-mno-avx5124vnniw’?
cc: error: unrecognized command line option ‘-mno-avx512vp2intersect’; did you mean ‘-mno-avx512vpopcntdq’?
cc: error: unrecognized command line option ‘-mno-avx512bf16’; did you mean ‘-mno-avx512bw’?
cc: error: unrecognized command line option ‘-mno-avx512bitalg’; did you mean ‘-mno-avx5124fmaps’?
cc: error: unrecognized command line option ‘-mno-avx512vbmi2’; did you mean ‘-mno-avx512vbmi’?
cc: error: unrecognized command line option ‘-mno-avx512vnni’; did you mean ‘-mno-avx5124vnniw’?
cc: error: unrecognized command line option ‘-mno-avx512vp2intersect’; did you mean ‘-mno-avx512vpopcntdq’?
cc: error: unrecognized command line option ‘-mno-avx512bf16’; did you mean ‘-mno-avx512bw’?
cc: error: unrecognized command line option ‘-mno-avx512bitalg’; did you mean ‘-mno-avx5124fmaps’?
cc: error: unrecognized command line option ‘-mno-avx512vbmi2’; did you mean ‘-mno-avx512vbmi’?
cc: error: unrecognized command line option ‘-mno-avx512vnni’; did you mean ‘-mno-avx5124vnniw’?
cc: error: unrecognized command line option ‘-mno-avx512vp2intersect’; did you mean ‘-mno-avx512vpopcntdq’?
make[3]: *** [extensions/gsOpennurbs/CMakeFiles/gsOpennurbs.dir/build.make:1445: extensions/gsOpennurbs/CMakeFiles/gsOpennurbs.dir/__/__/external/onurbs/opennurbs_memory.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1843: extensions/gsOpennurbs/CMakeFiles/gsOpennurbs.dir/all] Error 2


Tested g++versions

  *    7.5.0 compiles without problem
  *    8.3.1 crashes
  *    11.2.0 crashes

Steps to reproduce

  1.  Checkout G+Smo;
  2.  configure with cmake ../gismo -DCMAKE_BUILD_TYPE=Release -DGISMO_BUILD_UNITTESTS=ON -DGISMO_WITH_ONURBS=ON -DCMAKE_CXX_COMPILER=/path/to/g++;
  3.  compile with make unittests -j 8

**Comment by dominik-mokris-mtu** [comment]
Thank you, @mmoelle1. Interestingly, the problem does _not_ happen when compiling without OpenNurbs.

**Comment by osmihran** [comment]
I have updated the post with a few more tests on my home computer, HTH.

What I still don't understand is why the options seem to differ based on whether `GISMO_WITH_ONURBS` is `ON` or `OFF`. Where are they set? If they are set in `gismo/cmake/OptimizeForArchitecture.cmake` (as I had thought), wouldn't they be the same regardless of gsOpennurbs?

**Comment by dominik-mokris-mtu** [comment]
It seems that #577 has solved the issue. Here is an updated list of compiler tests.

**Updated list of compiler tests**
* [x]  g++ 7.5.0 (SUSE Linux) compiles without problem
* [x]  g++ 8.3.1 (SUSE Linux) compiles, used to crash
* [x]  g++ 9.4.0 (Ubuntu 20.04) TODO
* [x]  g++ 11.2.0 (SUSE Linux) compiles, used to crash
* [x]  clang 10.0 (Ubuntu 20.04) TODO
* [x]  clang++ 11.0.1 (SUSE Linux) crashes

My alter ego @osmihran will update the list with the tests on my home computer and, provided everything works, close the issue then.

**Comment by osmihran** [comment]
I have tested all the combinations and all work. Kudos to @mmoelle1 for #577 !
