### ISSUE TITLE
 How can I get the indices of active basis function on a surface within the model

### ISSUE THREAD

**Issue by Rennngw** [gismo/gismo#559]
hello,
I want to get the indices of active basis function on a inner plane of a model.
For example, I use **gsNurbsCreator<double>::BSplineCube(20, 0, 0, 0)** Creates a cube. Then I want to get the indices of basis function that is active on the physical Coordinates z = 0(parameter Coordinates w = 0.5) plane. How can I get it?
thanks!

![image](https://user-images.githubusercontent.com/110526351/203672472-95430373-d23e-4fa9-b29b-95491735d535.png)

**Comment by ckarampa** [comment]
Hi, are you interested in knowing the number of active basis functions only on isoparametric slices ( e.g. w=0.5 or v = 0.1 ) or on arbitrary planes in physical space?

**Comment by Rennngw** [comment]
Hi, I'm sorry I couldn't express my question clearly.
i want get the indices of active basis functions on isoparametric slices in three dimensional parameter space( e.g. w=0.5 )

**Comment by ckarampa** [comment]
Okay now it's a bit clearer. I have not done something similar and I do not know of a function that does precisely what you want ( although I might be wrong). I can think of a couple of ways you may go about it, reading [this Wiki page](https://gismo.github.io/group__Nurbs.html) will help you, If you haven't already. 

One method would be to pass a multitude ( enough to have at least one on each knot span) of parametric points that lie on your desired plane to the [`active_into()`](https://gismo.github.io/classgismo_1_1gsBasis.html#a7efde05f969b28f4ce7c984352708db7)  function of your basis. This will return a `gsMatrix` whose columns are the indices of the active basis functions at each point(column) you pass as input `u`. Then you need to figure out a way to remove the duplicate IDs. Of course this way is not very smart or efficient, but it will probably do the trick.

The other way is pretty much explained in the following example:
```c++
int main(int argc, char const *argv[])
{
    gsTensorBSpline<3>  cube = *gsNurbsCreator<>::BSplineCube(20, 0, 0, 0);
    cube.uniformRefine(1);   // Uniformly refine 2 times along all directions

    gsInfo <<"Total number of bases:" <<cube.basis().size()  << " = ";
    gsInfo << cube.basis().size(0) << "x" << cube.basis().size(1) << "x" << cube.basis().size(2) << "\n\n\n" ;


    index_t dir = 0; // Index of parametric direction which is normal to your plane

    gsMatrix<> value(1,1);
    value << 0.1;

    // Indices of the active basis functions in the univariate basis normal to your plane
    gsMatrix<> active_slices = cube.basis().component(dir).active(value);
    gsInfo << "Active 'slices' along direction " << dir << ": " << active_slices.transpose() << "\n\n\n";


    gsInfo << "Active bases on isoparametric plane normal to direction " << dir << " with value " << value << ":\n";
    for ( index_t i=0; i!= active_slices.rows(); i++)
    {
        gsInfo << cube.basis().coefSlice(dir,active_slices[i] ) <<"\n";
    }

    return 0; 
}
```

I believe this covers what you requested, let me know if something is unclear.

**Comment by Rennngw** [comment]
@ckarampa thanks you,my problem is solved. very thanks!

**Comment by Rennngw** [comment]
@ckarampa hi,I tried the following code to get  the indices of the basis functions that are nonzero at the domain boundary as single-column-matrix.

	auto bSpline = gsNurbsCreator<double>::BSplineCube(20.0, 0, 0, 0);

	bSpline->degreeElevate();

	for (int i = 0; i < 3; ++i)
		bSpline->uniformRefine();

	gsVector<index_t> westIdx = bSpline->basis().boundary(boundary::side::front);

the result is: from 0 to 99
0
1
2
3
...
99

then i tried the following code to get the indices of the basis functions that are nonzero on a isoparametric slice(e.g. w = 0).
This should get the same result like above, because the domain and the  isoparametric slice are same. right?
but the reuslt is : from 0 to 299

	auto bSpline = gsNurbsCreator<double>::BSplineCube(20.0, 0, 0, 0);

	bSpline->degreeElevate();

	for (int i = 0; i < 3; ++i)
		bSpline->uniformRefine();

	index_t dir = 2; // Index of parametric direction which is normal to your plane

	gsMatrix<double> value(1, 1);
	value << 0.0;

	// Indices of the active basis functions in the univariate basis normal to your plane
	gsBSplineBasis<double> base = bSpline->basis().component(2);
 	gsMatrix<index_t> active_slices = base.active(value);
	gsInfo << "Active 'slices' along direction " << dir << ": " << active_slices.transpose() << "\n\n\n";


	gsInfo << "Active bases on isoparametric plane normal to direction " << dir << " with value " << value << ":\n";
	for (index_t i = 0; i != active_slices.rows(); i++)
	{
		gsInfo << bSpline->basis().coefSlice(2, active_slices(i,0)) << "\n";
	}

result:
0
1
2
3
...
299

then i tried the third method: pass a multitude ( enough to have at least one on each knot span) of parametric points that lie on my desired plane (w = 0) to the [active_into()](https://gismo.github.io/classgismo_1_1gsBasis.html#a7efde05f969b28f4ce7c984352708db7) function of my basis.
the point i passed is :
0  0.125  0.25  0.375  0.5  0.625  0.75  0.875  1
0  0.125  0.25  0.375  0.5  0.625  0.75  0.875  1
0  0         0      0         0     0         0      0         0
and the result i got:
  0  11  22  33  44  55  66  77  77
  1  12  23  34  45  56  67  78  78
  2  13  24  35  46  57  68  79  79
 10  21  32  43  54  65  76  87  87
 11  22  33  44  55  66  77  88  88
 12  23  34  45  56  67  78  89  89
 20  31  42  53  64  75  86  97  97
 21  32  43  54  65  76  87  98  98
 22  33  44  55  66  77  88  99  99
100 111 122 133 144 155 166 177 177
101 112 123 134 145 156 167 178 178
102 113 124 135 146 157 168 179 179
110 121 132 143 154 165 176 187 187
111 122 133 144 155 166 177 188 188
112 123 134 145 156 167 178 189 189
120 131 142 153 164 175 186 197 197
121 132 143 154 165 176 187 198 198
122 133 144 155 166 177 188 199 199
200 211 222 233 244 255 266 277 277
201 212 223 234 245 256 267 278 278
202 213 224 235 246 257 268 279 279
210 221 232 243 254 265 276 287 287
211 222 233 244 255 266 277 288 288
212 223 234 245 256 267 278 289 289
220 231 242 253 264 275 286 297 297
221 232 243 254 265 276 287 298 298
222 233 244 255 266 277 288 299 299

it is from 0 to 299.

so why the result from first method is not same as the last two method?
is there something wrong of my understanding of the functiong boundary? It says its purpose is to return the indices of the basis functions that are nonzero at the domain boundary as single-column-matrix.

Very thanks for your help.

**Comment by ckarampa** [comment]
Hey, yes the first approach with ` bSpline->basis().boundary(boundary::side::front);` is technically correct. Your example has 1000 bases, 10 per direction, so you would expect to get 100 ids when you query for some of the external planes.

The error stems from the fact that when you call `active_slices = base.active(value);`  you get 3 ids in your example. Of course one of the three functions evaluate to 1 at your query point and the other two to 0 ( so technically they are inactive). This is a behaviour that is not going to be modified, it needs to be that way for other parts of the code to function properly.

One thing you can do is to check if the query value is 1 or 0 and handle that case with ` bSpline->basis().boundary(boundary::side::front);`. The other thing would be to also `eval()` the basis when you call  `active()` and then check if any basis function evaluates to zero. Then you can remove the respective id from the `active_slices` and you should be good to go. The second approach is more general I think. I hope that I answered your question. Please let me know if you need anything else, otherwise I will close the issue.

**Comment by Rennngw** [comment]
@ckarampa okay, thank you for your reply!
