### ISSUE TITLE
how to use  elementIndex function? 

### ISSUE THREAD

**Issue by Rennngw** [gismo/gismo#565]
Is there something wrong in elementindex function in gsTensorBasis.h ?

`size_t ElIndex = m_bases[d-1]->elementIndex( u.col(d-1) );`  **Should this col be changed to row?**

cause when i use this function, it will report an eigen exception.
maybe means the col index is out of range.

**Comment by ckarampa** [comment]
Can you provide a minimal example that replicates this? Also what is the exception?

**Comment by Rennngw** [comment]
yeah, my example like this:

```c++
auto bSpline = gsNurbsCreator<double>::BSplineCube(20, 0, 0, 0);
	bSpline->degreeElevate();

for (int i = 0; i < 2; ++i)
		bSpline->uniformRefine();

for (auto domIt = bSpline->basis().makeDomainIterator(); domIt->good(); domIt->next())
	{
		gsVector<double> center = domIt->centerPoint();
		std::cout << bSpline->basis().elementIndex(center);
	}
```

when i run this code, it can't success.
And i'm sorry i can't give you a description about the exception, because i have modified  the sorce code in my PC like: change "col" to "row". 
And after my modify, the running is success, and the result looks like is right also.

**Comment by Rennngw** [comment]
@ckarampa

**Comment by ckarampa** [comment]
I just ran this on my system, and it produces no errors, so I cannot replicate it. Can it be that your modifications have messed something up? Did you try running it in "stock" G+Smo ?
```c++
auto bSpline = gsNurbsCreator<>::BSplineCube(20, 0, 0, 0);
bSpline->degreeElevate();

for (int i = 0; i < 2; ++i)
bSpline->uniformRefine();

for (auto domIt = bSpline->basis().makeDomainIterator(); domIt->good(); domIt->next())
{
gsVector<> center = domIt->centerPoint();
std::cout << bSpline->basis().elementIndex(center);
}
```

**Comment by Rennngw** [comment]
@ckarampa Thanks!
And i'm sry, i am new to gismo.

But d is equal to 3, and u is a column vector with a column number of 1.
Why call "u.col (d-1)" wouldn't be out of his column range?

my exception is like this:
![image](https://user-images.githubusercontent.com/110526351/207055130-ab8c0c7f-e92a-4fa5-b90a-3ce6d5e1648a.png)

**Comment by ckarampa** [comment]
In the example you provided, there was no `d` or `u`, you used the `centerPoint`. Would you like to post the actual piece  of code thats causes this error ?

**Comment by Rennngw** [comment]
Sry sir, i mean when you use centerPoint call the function "elementindex(center)", like:

`bSpline->basis().elementIndex(center);`

it will turn up to the file "gsTensorBasis.h", right?

and in "gsTensorBasis.h",the implementation of the function elementindex:
https://github.com/gismo/gismo/blob/2e88baea42cdd34ab050e93f24acfe74f8cee4b9/src/gsTensor/gsTensorBasis.h#L138
u is the parameter i passed, here is centerPoint.

d is the base function dimension in the call statement, here is the dimension of bSpline->basis(), it is 3, right?

and my problem come out in gsTensorBasis.h

**Comment by Rennngw** [comment]
So d here is equal to 3, and u is a column vector with a column number of 1.
Why call "u.col (d-1)" wouldn't be out of his column range?

**Comment by Rennngw** [comment]
Sir, what is "stock" gismo by the way 
and very thanks for your help.

**Comment by ckarampa** [comment]
Sorry on the "stock" gismo comment, I didn't understand your question correctly.

  I see what you mean and you have a point. `u` is a column vector, so there is no point in traversing it's columns. 

@filiatra  Can you have a look? I believe this is indeed a bug, somehow on my system when `gsVector<3>::cols( )` is called, there is no error and a column vector is returned whose elements make no sense. I can make a PR out of it, as @Rennngw  pointed out, switching it to `.row()` seems to solve it, just need your approval.

**Comment by Rennngw** [comment]
@ckarampa Thanks and my english is bad.
Thank you for your help.
