### ISSUE TITLE
How to use elementInSupportOf function to get the correct result of an element？

### ISSUE THREAD

**Issue by Rennngw** [gismo/gismo#573]
My example code is as follows:

`

	auto bSpline = gsNurbsCreator<double>::BSplineCube(20, 0, 0, 0);
	bSpline->degreeElevate();
    for (int i = 0; i < 2; ++i)
		bSpline->uniformRefine();

	gsInfo << "bsplinebasis" << bSpline->basis();

       for (auto domIt = bSpline->basis().makeDomainIterator(); domIt->good(); domIt->next())
	{
		gsVector<double> center = domIt->centerPoint();
		size_t index = bSpline->basis().elementIndex(center);
		gsInfo << bSpline->basis().elementInSupportOf(index);
	}
`

The result obtained is not correct, how can I get the correct interval result.

**Comment by dominik-mokris-mtu** [comment]
Hello.

- What is the result that you get?
- Why do you think it is wrong?
- What would be the correct result?

**Comment by Rennngw** [comment]
@dominik-mokris-mtu

**Sry for not reply earlier.** 

**The result i got is:**
![image](https://user-images.githubusercontent.com/110526351/218251786-45f9532f-afc0-40c7-9d74-5fb0d8c37bb2.png)
which means:
first element: [0 0.25]x[0 0.25]x[0 0.25]
second element:[0.25 0.5]x[0 0.25]x[0 0.25]
third element:[0.25 0.5]x[0 0.25]x[0 0.25]
...
third element is same as second.is it wrong?

**I think the correct result is:**
first element: [0 0.25]x[0 0.25]x[0 0.25]
second element:[0.25 0.5]x[0 0.25]x[0 0.25]
third element:[0.5 0.75]x[0 0.25]x[0 0.25]
...

I'm not sure whether i'm right or wrong.
Thank you for your help in advance.

Best regards
Rennngw
