### ISSUE TITLE
thbSplineBasis using refine(gsMatrix) can not refine anything

### ISSUE THREAD

**Issue by Skygogogogo** [gismo/gismo#595]
real_t a = 0;                
    real_t b = 1;                
    unsigned interior = 3;      
    int      degree = 2;
    unsigned multEnd = degree + 1; 
    gsKnotVector<> kv(a, b, interior, multEnd);
    gsTensorBSplineBasis<2,real_t> tens( kv, kv );
    gsTHBSplineBasis<2,real_t> thb( tens );
    gsMatrix<real_t> boxM(2,2);
    boxM(0,0) = 0.25;
    boxM(1,0) = 0.0;

    boxM(0,1) = 1.0;
    boxM(1,1) = 0.5;

    thb.refine( boxM );
    gsWriteParaview(thb, ["thbbasis");]
    
![image](https://user-images.githubusercontent.com/106746289/227137101-90b9d315-779f-43d7-b84b-bdaf2ad25b09.png)

Please tell me how to solve this problem.

**Comment by ckarampa** [comment]
Hello, if you want to create this refined basis once ( and not do something iterative like adaptive refinement etc. ) you can do the following:
```
real_t a = 0;                
real_t b = 1;                
unsigned interior = 3;      
int      degree = 2;
unsigned multEnd = degree + 1; 
gsKnotVector<> kv(a, b, interior, multEnd);
gsTensorBSplineBasis<2,real_t> tens( kv, kv );
gsMatrix<real_t> boxM(2,2);
boxM(0,0) = 0.25;
boxM(1,0) = 0.0;

boxM(0,1) = 1.0;
boxM(1,1) = 0.5;

// thb.refine( boxM );
gsTHBSplineBasis<2,real_t> thb( tens, boxM );
gsWriteParaview(thb, "thbbasis");
```

**Comment by Skygogogogo** [comment]
Thank you for your reply, but I want to use this method to refine basis more than once.

**Comment by ckarampa** [comment]
You were right it is indeed a bug, I have spotted it. I will make a PR that fixes it today. Thanks for reporting it.
