### ISSUE TITLE
Linking gismo to another library that also use Eigen leads to  serious errors.

### ISSUE THREAD

**Issue by Skygogogogo** [gismo/gismo#601]
After compiling and installing gismo, linking to another library that also use Eigen leads to 
/usr/include/gismo/gsMatrix/Adjugate.h:160:33: error: no ‘const Eigen::internal::adjugate_impl<MatrixType> Eigen::MatrixBase<Derived>::adjugate() const’ member function declared in class ‘Eigen::MatrixBase<Derived>’
 MatrixBase<Derived>::adjugate() const
/usr/include/gismo/gsMatrix/Adjugate.h:167:50: error: no ‘void Eigen::MatrixBase<Derived>::adjugateInPlace()’ member function declared in class ‘Eigen::MatrixBase<Derived>’
 inline void MatrixBase<Derived>::adjugateInPlace()
some many errors that are not declared.

**Comment by Skygogogogo** [comment]
I have tried to make another depend not the copy of Eigen in /path/to/eigen but to gismo's Eigen in /path/to/gismo/external. But no effect, have same errors.

**Comment by Skygogogogo** [comment]
If I just link gismo to main.cpp, everything is going well. But once linking to other files that use Eigen led to no declared errors.

**Comment by Skygogogogo** [comment]
I also try this method https://github.com/gismo/gismo/compare/eigen_fix but no effect. Having same errors that no declared.

**Comment by Skygogogogo** [comment]
Wrapping the Eigen namespace inside gismo, whether it can solve the above problem. If can how to come true it.

**Comment by filiatra** [comment]
Hi, I started a fix in the branch gsEigen. You may already try it.
https://github.com/gismo/gismo/tree/gsEigen
 The Eigen namespace is renamed as gsEigen.
We will merge this later.

**Comment by dominik-mokris-mtu** [comment]
Related: #438
