### ISSUE TITLE
Could not build gsStructuralAnalysis module

### ISSUE THREAD

**Issue by miaodi** [gismo/gismo#609]
I am trying to compile g+smo with gsStructuralAnalysis so that I can play with the arc-length method. I pulled the latest gismo code and used `cmake .. -DGISMO_OPTIONAL="gsElasticity;gsKLShell;gsStructuralAnalysis;gsSpectra"` to download all needed modules.

When I compile the program, I get the following error:
<img width="705" alt="Screenshot 2023-05-04 204949" src="https://user-images.githubusercontent.com/9312314/236326087-a0d8847b-35d7-4fad-ae48-885baabda846.png">

I do not know if it is a bug or I miss some settings to get it work. Could someone help me out?

Thank you

**Comment by hverhelst** [comment]
Hi @miaodi , the easiest would be to remove the module gsElasticity from the CMake flag. Could you try that? I will have a look for a fix in the next days

**Comment by miaodi** [comment]
Hi @hverhelst, by removing gsElasticity, I can compile the library and examples that do not depend on gsElasticity.

Thank you
