### ISSUE TITLE
A small bug in gsMesh.

### ISSUE THREAD

**Issue by wj902911** [gismo/gismo#638]
https://github.com/gismo/gismo/blame/11099d23b1fd1f91f25a2de3940e29783e145610/src/gsUtils/gsMesh/gsMesh.hpp#L358
This line should be: next = addVertex(start + (T)(i + 1) * h * step);

**Comment by filiatra** [comment]
Solved, thanx !
https://github.com/gismo/gismo/commit/93a8813bbe57317debc7377bac90e84bbef01fee
