### ISSUE TITLE
How to use gismo with other libraries that use eigen?

### ISSUE THREAD

**Issue by Rennngw** [gismo/gismo#661]
I have compiled the latest version of gismo (the version that encapsulates Eigen into gsEigen), but when I use it, the project compiles and reports an error. 
The error is：
`
gismo\gsEigen\src\Eigenvalues\Tridiagonalization.h(20,14): error C3856: “traits”: is not a template class
gismo\gsEigen\src\Eigenvalues\Tridiagonalization.h(20,14): error C2065: “MatrixType”: undeclared identifier
...
...
`
Is there a correct way to use gismo with other libraries that use Eigen?
Hope you can help me, thank you very much.

**Comment by ckarampa** [comment]
Hi I am not familiar with your problem but #438 seems to be discussing this problem, hope this helps.

**Comment by filiatra** [comment]
Hi, it is hard to say what is wrong there...
Can you also post the full history and file include chain of the error ?

**Comment by Rennngw** [comment]
@filiatra @ckarampa  Hello, thank you very much for your reply. I solved this problem by checking previous related questions. I modified the three files: gismo.h, gsLinearAlgebra.h, and gsUndefEigenGuards.h. Maybe you can check my modifications. I don’t know if it is the right solution to the problem, for me personally it solved the problem.
[gismo.zip](https://github.com/gismo/gismo/files/13422600/gismo.zip)
