### ISSUE TITLE
question about gsElasticity module

### ISSUE THREAD

**Issue by Rennngw** [gismo/gismo#674]
### Discussed in https://github.com/gismo/gismo/discussions/673

<div type='discussions-op-text'>

<sup>Originally posted by **Rennngw** December 27, 2023</sup>
Dear All,
    I am a student from China. I'm studying gsElasticity module. I have one question to ask you.
    What I want to know is, in the gsElasticity module, what is the mathematical logic of linearElastic function in the gsElasticityFunctions.hpp file to solve the stress function of linear elasticity problem. Is there any paper on this aspect that I can study? I can’t understand it just by looking at the program. Thank you so much.

```template <class T>
void gsCauchyStressFunction<T>::linearElastic(const gsMatrix<T> & u, gsMatrix<T> & result) const
{
    result.setZero(targetDim(),outputCols(u.cols()));
    // evaluating the fields
    gsMapData<T> mdGeo(NEED_GRAD_TRANSFORM);
    mdGeo.points = u;
    m_geometry->patch(m_patch).computeMap(mdGeo);
    gsMapData<T> mdDisp(NEED_DERIV);
    mdDisp.points = u;
    m_displacement->patch(m_patch).computeMap(mdDisp);
    // define temporary matrices here for efficieny
    gsMatrix<T> I = gsMatrix<T>::Identity(m_dim,m_dim);
    gsMatrix<T> sigma,eps,dispGrad;
    // material parameters
    T YM = m_options.getReal("YoungsModulus");
    T PR = m_options.getReal("PoissonsRatio");
    T lambda = YM * PR / ( ( 1. + PR ) * ( 1. - 2. * PR ) );
    T mu     = YM / ( 2. * ( 1. + PR ) );

    for (index_t q = 0; q < u.cols(); ++q)
    {
        // linear strain tensor eps = (gradU+gradU^T)/2
        if (mdGeo.jacobian(q).determinant() <= 0)
            gsInfo << "Invalid domain parametrization: J = " << mdGeo.jacobian(q).determinant() <<
                      " at point (" << u.col(q).transpose() << ") of patch " << m_patch << std::endl;
        if (abs(mdGeo.jacobian(q).determinant()) > 1e-20)
           dispGrad = mdDisp.jacobian(q)*(mdGeo.jacobian(q).cramerInverse());
        else
            dispGrad = gsMatrix<T>::Zero(m_dim,m_dim);
        eps = (dispGrad + dispGrad.transpose())/2;
        // Cauchy stress tensor
        sigma = lambda*eps.trace()*I + 2*mu*eps;
        saveStress(sigma,result,q);
    }
}</div>

**Comment by wj902911** [comment]
This function is used when you have solved the displacement field and want to calculate stress field. The stresses are eventually computed through:
// Cauchy stress tensor
sigma = lambda*eps.trace()*I + 2*mu*eps;
It is basically this equation:
<img width="227" alt="sigma" src="https://github.com/gismo/gismo/assets/61172588/77a05fd7-6e40-45c3-af21-79c3613126c2">
The strains are calculated in this line:
eps = (dispGrad + dispGrad.transpose())/2;
which is the following equation:
<img width="194" alt="image" src="https://github.com/gismo/gismo/assets/61172588/4c0cb7f4-b8ef-4245-a3eb-83a9f602b910">
For these two equations, you can find them in Wikipedia under the term "Linear elasticity".
The purpose of all other lines above this one is to calculate displacement gradient. The most important one is:
dispGrad = mdDisp.jacobian(q)*(mdGeo.jacobian(q).cramerInverse());
And it is mathmatically this equation:
<img width="479" alt="image" src="https://github.com/gismo/gismo/assets/61172588/334c229a-bec8-434f-a198-c09daa9ef29d">
It is trying to transform displacement gradient from parametric domain to physical domain. To understand it, you need to read some books about FEM.
Hopefully this can help you.
