### ISSUE TITLE
Compiler error.

### ISSUE THREAD

**Issue by andre-caldas** [gismo/gismo#705]
I am getting that `dim` is a function, not a `short_t` variable. It should probably be `dim()`. Or `m_dim`...

https://github.com/gismo/gismo/blob/4d2819ad2e131cbfc527b1553635188b73cc63b4/src/gsModeling/gsTemplate.h#L588

I might be saying something silly, I've just met G+Smo a few hours ago. :-)

I have changed mine to `dim()` and it compiles, now. Looks like some sort of regression, but the sources have not been modified for a long time.

**Comment by hverhelst** [comment]
Hi @andre-caldas , 
Thanks for finding that one! I agree with you. Changing it to `dim()` or `m_dim` seems to be the same (according to `gsBoxTopology` so either of the two is a good fix. 
Could you make a PR closing this issue?
Thanks!
