### ISSUE TITLE
gsKnotVector<T>::degreeDecrease() for degree = 1

### ISSUE THREAD

**Issue by hhornik** [gismo/gismo#711]
The first part of the function:
    remove( ubegin()  , i );
    remove( uend() - 1, i );
    m_deg -= i;
does what I would expect. However, the second part, where the multiplicity of inner knots is checked and reduced if higher than m_deg, causes problems, since it removes (every other?) inner knots of multiplicity 1. 

Examples:
- for knot vector [ 0 0 1 1 ] it works fine
- for [ 0 0 1 2 2 ] -> segmentation fault
- for [ 0 0 1 2 3 3 ] -> [ 0 2 3 ]
- etc.

**Comment by weinmueller** [comment]
You can also see the discussion here #610
