### ISSUE TITLE
Build breaks: error: no member named 'data' in 'gsFeElement<T>'

### ISSUE THREAD

**Issue by yurivict** [gismo/gismo#741]
For questions use the [Q&A section](https://github.com/gismo/gismo/discussions/categories/q-a)

---

**Describe the bug**
```
In file included from /wrkdirs/usr/ports/math/gismo/work/gismo-24.08.0/src/gsAssembler/gsBiharmonicExprAssembler_.cpp:3:
In file included from /wrkdirs/usr/ports/math/gismo/work/gismo-24.08.0/src/gsAssembler/gsBiharmonicExprAssembler.h:16:
In file included from /wrkdirs/usr/ports/math/gismo/work/gismo-24.08.0/src/gsAssembler/gsExprAssembler.h:18:
In file included from /wrkdirs/usr/ports/math/gismo/work/gismo-24.08.0/src/gsAssembler/gsExprHelper.h:16:
/wrkdirs/usr/ports/math/gismo/work/gismo-24.08.0/src/gsAssembler/gsExpressions.h:843:15: error: no member named 'data' in 'gsFeElement<T>'
  843 |         this->data().flags |= NEED_VALUE;
      |         ~~~~  ^
1 error generated.
```

[log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p009a7c198ee2_s8d6feaaaa26/logs/gismo-24.08.0.log)

**To Reproduce**
build

**Desktop (please complete the following information):**
 - OS: FreeBSD 14.1
 - Branch/fork used: 24.08.0
 - clang-19

**Comment by mmoelle1** [comment]
I am currently trying to replicate the bug on my FreeBSD 13.2 system.

**Comment by yurivict** [comment]
The breakage is with clang-19. You should be able to reproduce it.
The cause is that non-existent class members are accessed in templetized methods that are never instantiated.

**Comment by mmoelle1** [comment]
@yurivict I can reproduce the error with clang-19. Strange that earlier versions don't spot this error. I'll create a PR.

BTW, do you know how to install a runner for either GitHub or GitLab on FreeBSD? I have a machine running FreeBSD 14.1 here that I could utilize as regular runner for G+Smo.

**Comment by ArashPartow** [comment]
@filiatra  I think this can be closed.

@yurivict  : https://github.com/freebsd/freebsd-ports/pull/326

**Comment by yurivict** [comment]
> BTW, do you know how to install a runner for either GitHub or GitLab on FreeBSD? I have a machine running FreeBSD 14.1 here that I could utilize as regular runner for G+Smo.

@mmoelle1 

* Cirrus CI supports FreeBSD: https://cirrus-ci.org/guide/FreeBSD/
* GitHub CI in FreeBSD: https://github.com/marketplace/actions/freebsd-vm
  * example: https://github.com/jcelerier/libremidi/actions/runs/5649349837/job/15303504636
  * example: https://github.com/votca/votca/blob/master/.github/workflows/freebsd.yml
