### ISSUE TITLE
when solving a poisson problem and the number of DoFs increasing, CompressedStorage.h has some errors

### ISSUE THREAD

**Issue by songbuling** [gismo/gismo#744]
When I use the gismo library to solve the Poisson problem, the code I used is the 2D example code, in the process of solving the P refinement to try to make the final numerical solution is closer to the exact solution, for a simple 3D model there is no problem, but for a complex 3D model, every time the number of DoFs is 7 digits, the program will be interrupted, jump to the The m_values[id] = v statement in the void append(const Scalar& v, Index i) function in the CompressedStorage.h file shows an illegal access, I'm guessing it's a vector memory problem and I'm eager to know how to solve this problem?

**Comment by ckarampa** [comment]
I am guessing that could be due to your system's memory, but @filiatra or @mmoelle1 probably know more about it.

**Comment by hverhelst** [comment]
I would suggest to compile gismo with higher precision integers and try again. I don't know why the integers already run out with 7 digits number of DoFs though.
To compile with higher precision on the integers, change the CMake option `GISMO_INDEX_TYPE` from `int` to `long int`.

**Comment by songbuling** [comment]
> I would suggest to compile gismo with higher precision integers and try again. I don't know why the integers already run out with 7 digits number of DoFs though. To compile with higher precision on the integers, change the CMake option `GISMO_INDEX_TYPE` from `int` to `long int`.

Thank you very much for your reply, I have followed your suggestion to recompile the index type and indeed the problem no longer occurs. Thanks again for your reply! ૮(˶ᵔ ᵕ ᵔ˶)ა
